import {createContext} from "react";

export const GlobalRentalContext = createContext();

export const rentalInfo = {
    carImg: "",
    carId: 0,
    carMake: "",
    carModel: "",
    carYear:"",
    transmissionType: "",
    seatCapacity: "",
    priceDaily: 0,
    branchId: 0,
    branchLocation: "",
    branchPhone: "",
    branchAddress: "",
    sortType: "",
    pickUpDate: "",
    dropoffDate :"",
    totalDays: 0,
    firstName: "",
    lastName:"",
    birthday: "",
    license: "",
    email: "",
    phoneNumber: "",
    pretotal: "",
    taxes: "",
    total: "",
    reservationDate: "",
    reservationId: 0,
    status: "",
    customerId: 0
}

export const fakeRentalInfoForContact = {
    carImg: "",
    carId: 0,
    carMake: "McQueen",
    carModel: "NX-245",
    carYear:"",
    transmissionType: "automatic",
    seatCapacity:0,
    branchLocation: "167 Mutual St Toronto",
    pickUpDate: "08-08-2022",
    dropoffDate :"10-08-2022",
    firstName: "",
    lastName:"",
    birthday: "",
    license: "",
    email: "",
    phoneNumber: "",
    total: 123,
    taxes: 30.43,
}